config/routes.rb
Rails.application.routes.draw do

  root to: "groups#index"

  get 'groups/:id/court', to: 'groups#court', as: :court

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :groups do
    resources :charges, only: [:new, :create, :destroy] do
      resources :sentences, only: [:new, :create]
    end
  end

  # get 'charges/destroy'
  # get 'sentences/destroy'

  # Current_user will commit
  get 'commitments/new'
  get 'commitments/create'
  get 'commitments/destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :user
  has_one :sentence

  validates :category, presence: true
  validates :description, presence: true
end

app/models/commitment.rb
class Commitment < ApplicationRecord
  has_many :user_commitments

  validates :category, presence: true
  validates :description, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :users, through: :user_groups
end

app/models/sentence.rb
class Sentence < ApplicationRecord
  belongs_to :charge
  has_one :user, through: :charge

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :charges
  has_many :sentences, through: :charges
  has_many :user_commitments
  has_many :commitments, through: :user_commitments
  has_many :user_groups
  has_many :groups, through: :user_groups

  def setting_total
    commitments.count.to_f + charges.count + sentences.count
  end

  def commitments_score
    score = (commitments.count.to_f / setting_total) * 100
    score.round
  end

  def charges_score
    score = (charges.count.to_f / setting_total) * 100
    score.round
  end

  def sentences_score
    score = (sentences.count.to_f / setting_total) * 100
    score.round
  end
end

app/models/user_charge.rb
class UserCharge < ApplicationRecord
  belongs_to :user
  belongs_to :charge
end

app/models/user_commitment.rb
class UserCommitment < ApplicationRecord
  belongs_to :user
  belongs_to :commitment
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_sentence.rb
class UserSentence < ApplicationRecord
  belongs_to :user
  belongs_to :sentence
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: :destroy

  def new
    @charge = Charge.new
  end

  def create
    @charge = Charge.new(charge_params)

    if @charge.save
      redirect_to request.referer
    else
      render :new
    end
  end

  def destroy
    @charge.destroy

    redirect_to court_path(params[:group_id])
  end

  private

  def set_charge
    @charge = Charge.find(params[:id])
  end

  def charge_params
    params.require(:charge).permit(:category, :description, :user_id)
  end
end

app/controllers/commitments_controller.rb
class CommitmentsController < ApplicationController
  before_action :set_commitment, only: :destroy

  def new
    @commitment = Commitment.new
  end

  def create
    @commitment = Commitment.new(commitment_params)

    if @commitment.save
      redirect_to request.referer
    else
      render :new
    end
  end

  def destroy
    @commitment.destroy

    redirect_to request.referer
  end

  private

  def set_commitment
    @commitment = Commitment.find(params[:id])
  end

  def commitment_params
    params.require(:commitment).permit(:category, :description)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  def new
    @sentence = Sentence.new
  end

  def create
    @sentence = Sentence.new(sentence_params)
    @sentence.charge = Charge.find(params[:charge_id])

    if @sentence.save
      redirect_to court_path(params[:group_id])
    else
      render :new
    end
  end

  def destroy
    @sentence.destroy
    redirect_to request.referer
  end

  private

  def sentence_params
    params.require(:sentence).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/commitments_helper.rb
module CommitmentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/destroy.html.erb
<h1>Charges#destroy</h1>
<p>Find me in app/views/charges/destroy.html.erb</p>

app/views/charges/new.html.erb
<h1>Charges#new</h1>
<p>Find me in app/views/charges/new.html.erb</p>

app/views/commitments/create.html.erb
<h1>Commitments#create</h1>
<p>Find me in app/views/commitments/create.html.erb</p>

app/views/commitments/destroy.html.erb
<h1>Commitments#destroy</h1>
<p>Find me in app/views/commitments/destroy.html.erb</p>

app/views/commitments/new.html.erb
<h1>Commitments#new</h1>
<p>Find me in app/views/commitments/new.html.erb</p>

app/views/groups/_lay_charges_partial.html.erb
<div class="container">
  <%= simple_form_for [@group, Charge.new] do |f| %>
  <div class="form-card">
    <%= f.input :user_id, as: :hidden, collection: @group.users.collect { |x|  [ x.id.to_i, x.username ] }, label_method: :second, value_method: :first, prompt: "Choose a User" %>
    <%= f.input :category, as: :radio_buttons, collection: ["Hygiene", "Media",
      "Information", "Social distancing", "Calm approach",
      "Fight boredom", "Positive focus", "Social connection", "Physical activity",
      "Work from home", "Tidying"] %>
    <%= f.input :description %>
    <%= f.button :submit, 'Lay Charge', class: "btn btn-primary mb-2" %>
  </div>
  <% end %>
</div>

app/views/groups/court.html.erb
<div class="banner-court">
</div>
</body>
  <div class="content-dashboard row m-0 p-0">
    <div class="col-0 col-lg-2 p-0 d-none d-lg-flex flex-column" style="position: sticky; flex: 1">
      <div style="height: 100vh; background-color: #224C8E">
        <%= render 'shared/left_sidebar' %>
      </div>
    </div>
    <div class="col-10 p-4 d-none d-lg-flex flex-column" style="position: sticky; flex: 1; height: 100vh; overflow: scroll">
      </html>
      <% team_users  = Group.find(params["id"].to_i ).users.all.collect{ |x| x.username } %>
      <% group_charges = Group.find(params["id"].to_i ).users.all.collect{ |x| x.charge_ids } %>
      <div class="container">
        <% team_users.each_with_index do |name, index| %>
        <div class="card text-center">
          <div class="card-header">
            <%= name.capitalize %>'s Charges
          </div>
          <div class="card-body">
            <% if group_charges[index].empty? %>
              <h5 class="card-title">Has no Charges Against</h5>
              <p class="card-text">Seems like they have been a good citizen</p>
            <% else %>
              <% group_charges[index].each do |charge| %>
              <% judge = (team_users.select{ |x| x != Charge.find(charge).user.username }).sample %>
                <% current_charge = Charge.find(charge) %>
                <h5 class="card-title">
                  Judge: <%= judge.capitalize %>
                </h5>
                <h5 class="card-title">
                  <%= current_charge.category %>
                  </h5>
                <p class="card-text"><%= current_charge.description %></p>

                <% if current_charge.sentence.nil? %>
                <%= link_to "Sentence", new_group_charge_sentence_path(Group.find(params[:id]), current_charge), class: "btn btn-primary" %>
                <%= link_to "Not Guilty", group_charge_path(Group.find(params[:id]), current_charge), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary" %>
                <% else %>
                <h5>Sentence: <%= current_charge.sentence.name %></h5>
                <% end %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
          </div>
        </div>
        <% end %>
        <%= link_to "Session Adjourned", group_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</body>

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/destroy.html.erb
<h1>Groups#destroy</h1>
<p>Find me in app/views/groups/destroy.html.erb</p>

app/views/groups/edit.html.erb
<h1>Groups#edit</h1>
<p>Find me in app/views/groups/edit.html.erb</p>

app/views/groups/index.html.erb
  <div class="col-0 col-lg-2 p-0 d-none d-lg-flex flex-column" style="position: sticky; flex: 1">
    <div style="height: 100vh; background-color: #224C8E">
      <%= render 'shared/left_sidebar' %>
    </div>
  </div>

  <div class="col-7 p-4 d-none d-lg-flex flex-column" style="position: sticky; flex: 1">
    <h1 class="dashboard-heading">Dashboard</h1>

    <h3 class="text-center">Your Teams</h3>
    <div class="team-cards">

    <% @groups.each do |group| %>
      <%= link_to group_path(group), :style => "text-decoration: none; color: black;" do %>
      <div class="card team-card">
        <h5><%= group.name %></h5>
        <p><%= group.users.count %> group members</p>
        <i class="fas fa-arrow-right"></i>
      </div>
      <% end %>
    <% end %>
    </div>

    <!-- <h3>Join a new team</h3>
    <p>Add form to join/create a new group</p> -->
    <div class="d-flex justify-content-center">
      <div class="btn btn-primary">Join a new team</div>
    </div>
  </div>

  <div class="col-3 p-4 d-none d-lg-flex flex-column" style="position: sticky; flex: 1; height: 100vh; overflow: scroll">
    <%= render partial: "shared/scoreboard" %>

    <%= render 'shared/commitments' %>
  </div>

app/views/groups/new.html.erb
<h1>Groups#new</h1>
<p>Find me in app/views/groups/new.html.erb</p>

app/views/groups/show.html.erb
<!-- <div class="content-dashboard row m-0 p-0" style="height: 100vh"> -->

  <div class="col-0 col-lg-2 p-0 d-none d-lg-flex flex-column" style="position: sticky; flex: 1">
    <div style="height: 100vh; background-color: #224C8E">
      <%= render 'shared/left_sidebar' %>
    </div>
  </div>

  <div class="col-8 p-4 d-none d-lg-flex flex-column" style="position: sticky; flex: 1; height: 100vh; overflow: scroll">
    <h3><%= @group.name %> <i class="fas fa-arrow-right"></i> <%= link_to "Start Trial", court_path(@group), class: "btn btn-secondary" %></h3>

    <div class="card-grid">
      <% Group.find(params[:id]).user_ids.each do |x| %>
        <% y = User.find(x) %>
        <div class="card" >
          <img src="https://scontent-syd2-1.xx.fbcdn.net/v/t1.0-9/38450845_10156744372604448_627472839087226880_o.jpg?_nc_cat=107&_nc_sid=85a577&_nc_oc=AQkUZMmVwxZwjPkeRpi3k6EC_unlitWNpevE8xA076-T0GbvQP7OHt8NlT4vTdodaZw&_nc_ht=scontent-syd2-1.xx&oh=2673d38eff95987d1fd8b0d4266956da&oe=5EB05447" class="card-img-top avatar" alt="...">
          <div class="card-body">
            <h5 class="card-title text-center mb-1"><%= y.username %></h5>
            <p class="card-text">
            <div class="score-bar d-flex flex-row">
              <div class="commitments-filler" style="width: <%= y.commitments_score %>%;">
              </div>
              <div class="charges-filler" style="width: <%= y.charges_score %>%;">
              </div>
            </div>
            <h6 class="card-subtitle mt-2 text-center"><%= y.commitments.count %> commitments</h6>
            <h6 class="card-subtitle mt-2 text-center"><%= y.charges.count %> charges</h6>
            <h6 class="card-subtitle mt-2 text-center"><%= y.sentences.count %> sentences</h6>
            </p>

            <!-- Modal button -->
            <div class="text-center">
              <button type="button" class="btn btn-primary my_link" id="btnModal" data-toggle="modal" data-target="#my-modal" data-val=<%= y.id %> data-name= <%= y.username %> >
                Snitch em up'
              </button>
            </div>

          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-2 p-1 d-none d-lg-flex flex-column" style="position: sticky; flex: 1; height: 100vh; overflow: scroll">
    <%= render partial: "shared/scoreboard" %>
    <%= render 'shared/commitments' %>
  </div>

</div>

<!-- Modal -->
<div class="modal fade" id="my-modal" tabindex="-1" role="dialog" aria-labelledby="my-modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLabel"></h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'lay_charges_partial' %>
      </div>
    </div>
  </div>


<script>
  modalbtns = document.querySelectorAll('#btnModal')

  modalbtns.forEach(btn => {
    btn.addEventListener('click', (event) => {
      let name = event.target.dataset["name"];
      let value = event.target.dataset["val"];

      document.querySelector(".modal-title").innerText = "Snitch " + name;
      document.getElementById("charge_user_id").value = value;
    });
  });
</script>

app/views/sentences/create.html.erb
<h1>Sentences#create</h1>
<p>Find me in app/views/sentences/create.html.erb</p>

app/views/sentences/destroy.html.erb
<h1>Sentences#destroy</h1>
<p>Find me in app/views/sentences/destroy.html.erb</p>

app/views/sentences/new.html.erb
<div class="container">
  <div>
    <h1>Sentencing</h1>
  </div>
  <%= simple_form_for [Group.find(params[:group_id]), Charge.find(params[:charge_id]), @sentence] do |f| %>
  <div class="form-card">
    <%= f.input :name, label: 'Conviction' %>
    <div class="btn btn-primary">
      <%= f.button :submit, 'Convict' %>
    </div>
  </div>
    <% end %>
</div>