config/routes.rb
Rails.application.routes.draw do

  root to: "groups#index"

  get 'groups/:id/court', to: 'groups#court', as: :court

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :groups do
    resources :charges, only: [:new, :create, :destroy] do
      resources :sentences, only: [:new, :create]
    end
  end

  # get 'charges/destroy'
  # get 'sentences/destroy'

  # Current_user will commit
  get 'commitments/new'
  get 'commitments/create'
  get 'commitments/destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :user
  has_one :sentence

  validates :category, presence: true
  validates :description, presence: true
end

app/models/commitment.rb
class Commitment < ApplicationRecord
  has_many :user_commitments

  validates :category, presence: true
  validates :description, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :users, through: :user_groups
end

app/models/sentence.rb
class Sentence < ApplicationRecord
  belongs_to :charge
  has_one :user, through: :charge

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :charges
  has_many :sentences, through: :charges
  has_many :user_commitments
  has_many :commitments, through: :user_commitments
  has_many :user_groups
  has_many :groups, through: :user_groups

  def setting_total
    commitments.count.to_f + charges.count + sentences.count
  end

  def commitments_score
    score = (commitments.count.to_f / setting_total) * 100
    score.round
  end

  def charges_score
    score = (charges.count.to_f / setting_total) * 100
    score.round
  end

  def sentences_score
    score = (sentences.count.to_f / setting_total) * 100
    score.round
  end
end

app/models/user_charge.rb
class UserCharge < ApplicationRecord
  belongs_to :user
  belongs_to :charge
end

app/models/user_commitment.rb
class UserCommitment < ApplicationRecord
  belongs_to :user
  belongs_to :commitment
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_sentence.rb
class UserSentence < ApplicationRecord
  belongs_to :user
  belongs_to :sentence
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: :destroy

  def new
    @charge = Charge.new
  end

  def create
    @charge = Charge.new(charge_params)

    if @charge.save
      redirect_to request.referer
    else
      render :new
    end
  end

  def destroy
    @charge.destroy

    redirect_to court_path(params[:group_id])
  end

  private

  def set_charge
    @charge = Charge.find(params[:id])
  end

  def charge_params
    params.require(:charge).permit(:category, :description, :user_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  def new
    @sentence = Sentence.new
  end

  def create
    @sentence = Sentence.new(sentence_params)
    @sentence.charge = Charge.find(params[:charge_id])

    if @sentence.save
      redirect_to court_path(params[:group_id])
    else
      render :new
    end
  end

  def destroy
    @sentence.destroy
    redirect_to request.referer
  end

  private

  def sentence_params
    params.require(:sentence).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/commitments_helper.rb
module CommitmentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IsoCourt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  </head>

  <body>
    <div class="content-dashboard row m-0 p-0" style="height: 100vh">
    <%#= render 'shared/navbar' %>

    <%= yield %>

    <p class="notice" style="z-index: 1; position: fixed"><%= notice %></p>
    <p class="alert" style="z-index: 1; position: fixed"><%= alert %></p>

    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Home</h1>

<%= render partial: "shared/navbar" %>

app/views/shared/_commitments.html.erb
<div class="card text-white bg-info mb-3" style="max-width: 18rem;">
  <div class="card-header">Weekly Commitment </div>
  <div class="card-body">
    <p class="card-text"><%= current_user.commitments.last.description %></p>
  </div>
</div>
<div class="card text-white bg-info mb-3" style="max-width: 18rem;">
  <div class="card-header"> Charges Against </div>
  <% if current_user.charge_ids.empty? %>
  <div class="card-body">
    <p class="card-text">No Sentences this week :)</p>
  </div>
  <% else %>
  <div class="card-body">
    <% current_user.charge_ids.each do |id| %>
      <p class="card-text"><%= Charge.find(id).category %>: <%= Charge.find(id).description %></p>
    <% end %>
  </div>
  <% end %>
</div>
<div class="card text-white bg-info mb-3" style="max-width: 18rem;">
  <div class="card-header">Weekly Sentence's </div>

  <% if current_user.sentence_ids.empty? %>
  <div class="card-body">
    <p class="card-text">No Sentences this week :)</p>
  </div>
  <% else %>
  <div class="card-body">
    <% current_user.sentence_ids.each do |id| %>
      <p class="card-text"><%= Sentence.find(id).name %></p>
    <% end %>
  </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_group-container.html.erb
group-container.html.erb

app/views/shared/_laws.html.erb
_laws.html.erb

app/views/shared/_left_sidebar.html.erb
<nav class="nav flex-column">
  <%= link_to "Home", root_path, class: "nav-link active" %>
  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
</nav>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_process-container.html.erb
_process-container.html.erb

app/views/shared/_scoreboard.html.erb
<div class="card score-card container-fluid mt-2 mb-2">
  <div class="card-body p-1 m-1">
    <h5 class="card-title text-center mt-3 mb-3">SCOREBOARD</h5>

    <div class="score-bar d-flex flex-row">
      <div class="commitments-filler" style="width: <%= current_user.commitments_score %>%;">
      </div>
      <div class="charges-filler" style="width: <%= current_user.charges_score %>%;">
      </div>
    </div>
    <br>
    <!-- <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6> -->
    <h6 class="card-subtitle mt-2 mb-3 text-center"><%= current_user.commitments.count %> commitments</h6>
    <h6 class="card-subtitle mb-3 text-center"><%= current_user.charges.count %> charges</h6>
    <h6 class="card-subtitle mb-3 text-center"><%= current_user.sentences.count %> sentences</h6>
  </div>
</div>